### ISSUE TITLE
How to get R1M_R101_GeM.pkl and R1M_R101_DELG.pkl ?

### ISSUE THREAD

**Issue by SeunghanYu** [MCC-WH/SSP#1]
Hi, @MCC-WH,
I'm encountering an issue in the SSP code related to the generation of anchor points.
For generating anchor points, this code requires files named **R1M_R101_GeM.pkl** and **R1M_R101_DELG.pkl**, which I can't find.
Could you provide the separate code to generate these files?
Alternatively, is it possible to obtain the **R1M_R101_GeM.pkl** or **R1M_R101_DELG.pkl** files directly?

Looking forward to your reply. Thank you in advance!

**Comment by MCC-WH** [comment]
Thanks for your interesting. You can fine the code and model at [Filip Radenovic's great repository on image retrieval](https://github.com/filipradenovic/cnnimageretrieval-pytorch). For 'R1M_R101_GeM.pkl', the model is released at [R101-DELG](https://drive.google.com/file/d/10WExWiY5cc4-hrQQpQ3yUvOV06f3wYaB/view?usp=sharing).

**Comment by SeunghanYu** [comment]
@MCC-WH

Thank you for your quick response.
I have another question regarding the process of creating the **R1M_R101_GeM.pkl** file.

The R1M dataset consists of 1,001,001 images.
Is it correct to extract the image features from all 1,001,001 images, save them into the R1M_R101_GeM.pkl file, and then use this file to generate Anchor Points?"

**Comment by MCC-WH** [comment]
Yes, and you can also sample some images to generate anchor points, which saves time and computational overhead.

**Comment by SeunghanYu** [comment]
Thank you!
I made a code to extract R1M features and successfully get R1M_R101_GeM.pkl and R1M_R101_DELG.pkl.
