### ISSUE TITLE
CSD_training

### ISSUE THREAD

**Issue by SeunghanYu** [MCC-WH/SSP#2]
Hi, @MCC-WH

In TABLE 2 of the paper, it's mentioned that training was conducted using the Contextual Similarity Distillation (CSD) method, and the mAP performance metrics were compared.
However, it appears that there is no CSD_training.py file included in the code repository.
Is the code related to the CSD training method not provided, or am I missing something?

Looking forward to your reply. Thank you in advance!

**Comment by MCC-WH** [comment]
In fact the CSD training is almost identical to the current method, except that you need to get the corresponding anchor_feature, you can try to modify the dataloader according to the CSD paper , ie., constructing a faiss index for the nearest neighbor retrieval.

**Comment by SeunghanYu** [comment]
Thank you for your reply!
I'll work on making CSD_training.py based on the CSD paper, thanks to your advice.
